name: TPMM
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - bzip2=1.0.8=hda65f42_9
  - ca-certificates=2026.2.25=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.4=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_18
  - libgcc-ng=15.2.0=h69a702a_18
  - libgfortran=15.2.0=h69a702a_18
  - libgfortran5=15.2.0=h68bc16d_18
  - libgomp=15.2.0=he0feb66_18
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_18
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.2=py311h2e04523_1
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.1=py311h8032f78_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.11.14=hd63d673_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - readline=8.3=h853b02a_0
  - scipy=1.17.1=py311hbe70eeb_0
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6